insert into Assignment (assignment_name, points, category_id) values ('Crum''s Candle Snuffer Moss', 34, 72);
insert into Assignment (assignment_name, points, category_id) values ('Whiteflower Leafcup', 70, 54);
insert into Assignment (assignment_name, points, category_id) values ('Howell''s Pioneer Rockcress', 23, 27);
insert into Assignment (assignment_name, points, category_id) values ('Greene''s Goldenbush', 35, 23);
insert into Assignment (assignment_name, points, category_id) values ('Chamisso''s Manfern', 53, 37);
insert into Assignment (assignment_name, points, category_id) values ('Whorled Marshpennywort', 36, 10);
insert into Assignment (assignment_name, points, category_id) values ('Barrett''s Beardtongue', 38, 18);
insert into Assignment (assignment_name, points, category_id) values ('Slender Bird''s Beak', 33, 69);
insert into Assignment (assignment_name, points, category_id) values ('Adam And Eve', 31, 39);
insert into Assignment (assignment_name, points, category_id) values ('Stiff Yellow Flax', 45, 93);
insert into Assignment (assignment_name, points, category_id) values ('Lecidea Lichen', 11, 18);
insert into Assignment (assignment_name, points, category_id) values ('Kellogg''s Sedge', 67, 90);
insert into Assignment (assignment_name, points, category_id) values ('Purple Amaranth', 4, 42);
insert into Assignment (assignment_name, points, category_id) values ('Boom''s Quillwort', 79, 100);
insert into Assignment (assignment_name, points, category_id) values ('Littleflower Ipomopsis', 20, 54);
