insert into Assignment (assignment_name, points, category_id) values ('Crum''s Candle Snuffer Moss', 34, 7);
insert into Assignment (assignment_name, points, category_id) values ('Whiteflower Leafcup', 70, 5);
insert into Assignment (assignment_name, points, category_id) values ('Howell''s Pioneer Rockcress', 23, 7);
insert into Assignment (assignment_name, points, category_id) values ('Greene''s Goldenbush', 35, 2);
insert into Assignment (assignment_name, points, category_id) values ('Chamisso''s Manfern', 53, 7);
insert into Assignment (assignment_name, points, category_id) values ('Whorled Marshpennywort', 36, 10);
insert into Assignment (assignment_name, points, category_id) values ('Barrett''s Beardtongue', 38, 1);
insert into Assignment (assignment_name, points, category_id) values ('Slender Bird''s Beak', 33, 6);
insert into Assignment (assignment_name, points, category_id) values ('Adam And Eve', 31, 9);
insert into Assignment (assignment_name, points, category_id) values ('Stiff Yellow Flax', 45, 9);
insert into Assignment (assignment_name, points, category_id) values ('Lecidea Lichen', 11, 8);
insert into Assignment (assignment_name, points, category_id) values ('Kellogg''s Sedge', 67, 9);
insert into Assignment (assignment_name, points, category_id) values ('Purple Amaranth', 4, 4);
insert into Assignment (assignment_name, points, category_id) values ('Boom''s Quillwort', 79, 10);
insert into Assignment (assignment_name, points, category_id) values ('Littleflower Ipomopsis', 20, 4);
insert into Assignment (assignment_name, points, category_id) values ('Variable-leaf Ticktrefoil', 96, 1);
insert into Assignment (assignment_name, points, category_id) values ('Sweet Woodreed', 67, 5);
insert into Assignment (assignment_name, points, category_id) values ('Rocky Mountain Buttercup', 48, 8);
insert into Assignment (assignment_name, points, category_id) values ('Okie Bean', 81, 10);
insert into Assignment (assignment_name, points, category_id) values ('Lac Tree', 74, 4);
insert into Assignment (assignment_name, points, category_id) values ('Sweet Fennel', 9, 2);
insert into Assignment (assignment_name, points, category_id) values ('Dicranum Moss', 78, 10);
insert into Assignment (assignment_name, points, category_id) values ('Purpleflower Pinkroot', 27, 1);
insert into Assignment (assignment_name, points, category_id) values ('Arthothelium Lichen', 50, 1);
insert into Assignment (assignment_name, points, category_id) values ('California Draba', 25, 7);
insert into Assignment (assignment_name, points, category_id) values ('Bitter Snakewood', 51, 9);
insert into Assignment (assignment_name, points, category_id) values ('Sandpuffs', 50, 10);
insert into Assignment (assignment_name, points, category_id) values ('Lignum-vitae', 100, 10);
insert into Assignment (assignment_name, points, category_id) values ('Narrow-leaved Iceplant', 99, 3);
insert into Assignment (assignment_name, points, category_id) values ('Niruri', 32, 3);
insert into Assignment (assignment_name, points, category_id) values ('Umbrella Catchbirdtree', 40, 2);
insert into Assignment (assignment_name, points, category_id) values ('Santa Barbara Ceanothus', 22, 1);
insert into Assignment (assignment_name, points, category_id) values ('False Mayweed', 54, 10);
insert into Assignment (assignment_name, points, category_id) values ('Fredonia Buckwheat', 98, 4);
insert into Assignment (assignment_name, points, category_id) values ('Showy Cappel', 42, 7);
insert into Assignment (assignment_name, points, category_id) values ('Montane Rockcap Fern', 81, 5);
insert into Assignment (assignment_name, points, category_id) values ('Longan', 58, 2);
insert into Assignment (assignment_name, points, category_id) values ('Little Larkspur', 39, 5);
insert into Assignment (assignment_name, points, category_id) values ('Calkins'' Wart Lichen', 6, 1);
insert into Assignment (assignment_name, points, category_id) values ('Coastal Sandmat', 37, 8);
insert into Assignment (assignment_name, points, category_id) values ('Beard Lichen', 97, 6);
insert into Assignment (assignment_name, points, category_id) values ('China Tortula Moss', 34, 3);
insert into Assignment (assignment_name, points, category_id) values ('Gaspé Peninsula Bluegrass', 4, 2);
insert into Assignment (assignment_name, points, category_id) values ('Eggyolk Lichen', 58, 6);
insert into Assignment (assignment_name, points, category_id) values ('Brazilian Nightshade', 17, 3);
insert into Assignment (assignment_name, points, category_id) values ('Cane', 38, 6);
insert into Assignment (assignment_name, points, category_id) values ('Spirea', 27, 1);
insert into Assignment (assignment_name, points, category_id) values ('Lemon', 53, 10);
insert into Assignment (assignment_name, points, category_id) values ('Chilghoza Pine', 35, 5);
insert into Assignment (assignment_name, points, category_id) values ('Nevada Willowherb', 61, 5);
insert into Assignment (assignment_name, points, category_id) values ('Merrill''s Rim Lichen', 81, 2);
insert into Assignment (assignment_name, points, category_id) values ('Puerto Rico Hempvine', 59, 7);
insert into Assignment (assignment_name, points, category_id) values ('Dwarf Morning-glory', 8, 9);
insert into Assignment (assignment_name, points, category_id) values ('Twocarpel Dwarf-flax', 26, 4);
insert into Assignment (assignment_name, points, category_id) values ('Bryobrittonia Moss', 28, 9);
insert into Assignment (assignment_name, points, category_id) values ('Tetragastris', 86, 9);
insert into Assignment (assignment_name, points, category_id) values ('Shy Wallflower', 54, 10);
insert into Assignment (assignment_name, points, category_id) values ('Sessileleaf Stopper', 51, 1);
insert into Assignment (assignment_name, points, category_id) values ('Death Valley Beardtongue', 17, 3);
insert into Assignment (assignment_name, points, category_id) values ('Southern Flax', 93, 8);
insert into Assignment (assignment_name, points, category_id) values ('Cynodontium Moss', 55, 7);
insert into Assignment (assignment_name, points, category_id) values ('Palisota', 22, 9);
insert into Assignment (assignment_name, points, category_id) values ('Engelmann''s Hedgehog Cactus', 46, 5);
insert into Assignment (assignment_name, points, category_id) values ('Island Brittleleaf', 47, 3);
insert into Assignment (assignment_name, points, category_id) values ('Bluntpod Bundleflower', 11, 4);
insert into Assignment (assignment_name, points, category_id) values ('Fiveminute Grass', 74, 4);
insert into Assignment (assignment_name, points, category_id) values ('Lakeshore Bulrush', 94, 1);
insert into Assignment (assignment_name, points, category_id) values ('Mesa Pepperwort', 7, 1);
insert into Assignment (assignment_name, points, category_id) values ('Sheep Fescue', 8, 8);
insert into Assignment (assignment_name, points, category_id) values ('Caribbean Caltrop', 73, 7);
insert into Assignment (assignment_name, points, category_id) values ('Woodland Crocus', 99, 6);
insert into Assignment (assignment_name, points, category_id) values ('Upright Blue Beardtongue', 60, 8);
insert into Assignment (assignment_name, points, category_id) values ('Grayhairy Wild Indigo', 29, 2);
insert into Assignment (assignment_name, points, category_id) values ('Stokes'' Aster', 84, 1);
insert into Assignment (assignment_name, points, category_id) values ('Isachne', 90, 2);
insert into Assignment (assignment_name, points, category_id) values ('Mountain Thistle', 54, 5);
insert into Assignment (assignment_name, points, category_id) values ('Contorted Skin Lichen', 91, 8);
insert into Assignment (assignment_name, points, category_id) values ('Clausen''s Violet', 24, 7);
insert into Assignment (assignment_name, points, category_id) values ('Siberian Spikemoss', 11, 6);
insert into Assignment (assignment_name, points, category_id) values ('Fall Dandelion', 3, 4);
insert into Assignment (assignment_name, points, category_id) values ('Maxon''s Peperomia', 47, 2);
insert into Assignment (assignment_name, points, category_id) values ('Entireleaved Thelypody', 55, 1);
insert into Assignment (assignment_name, points, category_id) values ('Coastal Wattle', 32, 8);
insert into Assignment (assignment_name, points, category_id) values ('Koehler''s Rockcress', 28, 3);
insert into Assignment (assignment_name, points, category_id) values ('Spoonleaf Cyanea', 55, 1);
insert into Assignment (assignment_name, points, category_id) values ('Desert Springparsley', 56, 7);
insert into Assignment (assignment_name, points, category_id) values ('Recurved Bryoerythrophyllum Moss', 54, 8);
insert into Assignment (assignment_name, points, category_id) values ('Trachycystis Moss', 79, 4);
insert into Assignment (assignment_name, points, category_id) values ('Kidneyshape Buckwheat', 89, 7);
insert into Assignment (assignment_name, points, category_id) values ('Mountain Ball Cactus', 18, 10);
insert into Assignment (assignment_name, points, category_id) values ('Jeweled Distaff Thistle', 28, 3);
insert into Assignment (assignment_name, points, category_id) values ('Rough Potato', 79, 10);
insert into Assignment (assignment_name, points, category_id) values ('Storm Sedge', 30, 9);
insert into Assignment (assignment_name, points, category_id) values ('Holboell''s Rockcress', 54, 9);
insert into Assignment (assignment_name, points, category_id) values ('Wyoming Sand Verbena', 46, 1);
insert into Assignment (assignment_name, points, category_id) values ('Beaked Skeletonweed', 62, 10);
insert into Assignment (assignment_name, points, category_id) values ('European Vetch', 77, 2);
insert into Assignment (assignment_name, points, category_id) values ('American Alumroot', 53, 8);
insert into Assignment (assignment_name, points, category_id) values ('Yampa Beardtongue', 58, 7);
insert into Assignment (assignment_name, points, category_id) values ('Red Monkswort', 45, 3);
