insert into Category (category_id, category_name, weight, course_id) values (1, 'homework', 65, 50);
insert into Category (category_id, category_name, weight, course_id) values (2, 'extra credit', 15, 63);
insert into Category (category_id, category_name, weight, course_id) values (3, 'test', 83, 75);
insert into Category (category_id, category_name, weight, course_id) values (4, 'test', 17, 41);
insert into Category (category_id, category_name, weight, course_id) values (5, 'volunteer', 68, 69);
insert into Category (category_id, category_name, weight, course_id) values (6, 'project', 84, 49);
insert into Category (category_id, category_name, weight, course_id) values (7, 'project', 100, 41);
insert into Category (category_id, category_name, weight, course_id) values (8, 'extra credit', 49, 39);
insert into Category (category_id, category_name, weight, course_id) values (9, 'extra credit', 70, 13);
insert into Category (category_id, category_name, weight, course_id) values (10, 'test', 69, 55);
insert into Category (category_id, category_name, weight, course_id) values (11, 'extra credit', 55, 64);
insert into Category (category_id, category_name, weight, course_id) values (12, 'quiz', 92, 75);
insert into Category (category_id, category_name, weight, course_id) values (13, 'extra credit', 85, 80);
insert into Category (category_id, category_name, weight, course_id) values (14, 'homework', 94, 9);
insert into Category (category_id, category_name, weight, course_id) values (15, 'quiz', 99, 85);
insert into Category (category_id, category_name, weight, course_id) values (16, 'quiz', 26, 21);
insert into Category (category_id, category_name, weight, course_id) values (17, 'volunteer', 29, 97);
insert into Category (category_id, category_name, weight, course_id) values (18, 'homework', 37, 98);
insert into Category (category_id, category_name, weight, course_id) values (19, 'test', 95, 12);
insert into Category (category_id, category_name, weight, course_id) values (20, 'project', 28, 50);
insert into Category (category_id, category_name, weight, course_id) values (21, 'volunteer', 87, 100);
insert into Category (category_id, category_name, weight, course_id) values (22, 'project', 65, 80);
insert into Category (category_id, category_name, weight, course_id) values (23, 'volunteer', 31, 44);
insert into Category (category_id, category_name, weight, course_id) values (24, 'homework', 75, 78);
insert into Category (category_id, category_name, weight, course_id) values (25, 'extra credit', 28, 21);
insert into Category (category_id, category_name, weight, course_id) values (26, 'project', 74, 57);
insert into Category (category_id, category_name, weight, course_id) values (27, 'project', 51, 54);
insert into Category (category_id, category_name, weight, course_id) values (28, 'volunteer', 57, 25);
insert into Category (category_id, category_name, weight, course_id) values (29, 'volunteer', 89, 14);
insert into Category (category_id, category_name, weight, course_id) values (30, 'test', 83, 53);
insert into Category (category_id, category_name, weight, course_id) values (31, 'project', 44, 32);
insert into Category (category_id, category_name, weight, course_id) values (32, 'quiz', 97, 82);
insert into Category (category_id, category_name, weight, course_id) values (33, 'volunteer', 79, 22);
insert into Category (category_id, category_name, weight, course_id) values (34, 'project', 10, 23);
insert into Category (category_id, category_name, weight, course_id) values (35, 'project', 61, 35);
insert into Category (category_id, category_name, weight, course_id) values (36, 'extra credit', 13, 66);
insert into Category (category_id, category_name, weight, course_id) values (37, 'test', 29, 95);
insert into Category (category_id, category_name, weight, course_id) values (38, 'homework', 11, 32);
insert into Category (category_id, category_name, weight, course_id) values (39, 'extra credit', 86, 53);
insert into Category (category_id, category_name, weight, course_id) values (40, 'test', 18, 43);
insert into Category (category_id, category_name, weight, course_id) values (41, 'homework', 21, 40);
insert into Category (category_id, category_name, weight, course_id) values (42, 'project', 23, 71);
insert into Category (category_id, category_name, weight, course_id) values (43, 'project', 63, 56);
insert into Category (category_id, category_name, weight, course_id) values (44, 'homework', 96, 80);
insert into Category (category_id, category_name, weight, course_id) values (45, 'project', 99, 51);
insert into Category (category_id, category_name, weight, course_id) values (46, 'homework', 39, 39);
insert into Category (category_id, category_name, weight, course_id) values (47, 'homework', 55, 11);
insert into Category (category_id, category_name, weight, course_id) values (48, 'project', 38, 8);
insert into Category (category_id, category_name, weight, course_id) values (49, 'volunteer', 46, 29);
insert into Category (category_id, category_name, weight, course_id) values (50, 'homework', 36, 61);
insert into Category (category_id, category_name, weight, course_id) values (51, 'test', 88, 44);
insert into Category (category_id, category_name, weight, course_id) values (52, 'project', 89, 80);
insert into Category (category_id, category_name, weight, course_id) values (53, 'project', 83, 87);
insert into Category (category_id, category_name, weight, course_id) values (54, 'quiz', 75, 93);
insert into Category (category_id, category_name, weight, course_id) values (55, 'quiz', 64, 9);
insert into Category (category_id, category_name, weight, course_id) values (56, 'test', 24, 70);
insert into Category (category_id, category_name, weight, course_id) values (57, 'quiz', 16, 13);
insert into Category (category_id, category_name, weight, course_id) values (58, 'homework', 94, 91);
insert into Category (category_id, category_name, weight, course_id) values (59, 'test', 86, 49);
insert into Category (category_id, category_name, weight, course_id) values (60, 'volunteer', 35, 40);
insert into Category (category_id, category_name, weight, course_id) values (61, 'quiz', 14, 24);
insert into Category (category_id, category_name, weight, course_id) values (62, 'homework', 75, 98);
insert into Category (category_id, category_name, weight, course_id) values (63, 'test', 99, 84);
insert into Category (category_id, category_name, weight, course_id) values (64, 'project', 11, 43);
insert into Category (category_id, category_name, weight, course_id) values (65, 'volunteer', 30, 87);
insert into Category (category_id, category_name, weight, course_id) values (66, 'homework', 64, 77);
insert into Category (category_id, category_name, weight, course_id) values (67, 'volunteer', 38, 98);
insert into Category (category_id, category_name, weight, course_id) values (68, 'homework', 46, 72);
insert into Category (category_id, category_name, weight, course_id) values (69, 'quiz', 65, 52);
insert into Category (category_id, category_name, weight, course_id) values (70, 'test', 98, 68);
insert into Category (category_id, category_name, weight, course_id) values (71, 'project', 45, 14);
insert into Category (category_id, category_name, weight, course_id) values (72, 'quiz', 39, 35);
insert into Category (category_id, category_name, weight, course_id) values (73, 'quiz', 30, 29);
insert into Category (category_id, category_name, weight, course_id) values (74, 'homework', 51, 38);
insert into Category (category_id, category_name, weight, course_id) values (75, 'homework', 87, 13);
insert into Category (category_id, category_name, weight, course_id) values (76, 'homework', 81, 71);
insert into Category (category_id, category_name, weight, course_id) values (77, 'extra credit', 85, 36);
insert into Category (category_id, category_name, weight, course_id) values (78, 'homework', 23, 93);
insert into Category (category_id, category_name, weight, course_id) values (79, 'homework', 38, 35);
insert into Category (category_id, category_name, weight, course_id) values (80, 'test', 30, 77);
insert into Category (category_id, category_name, weight, course_id) values (81, 'extra credit', 46, 39);
insert into Category (category_id, category_name, weight, course_id) values (82, 'test', 56, 35);
insert into Category (category_id, category_name, weight, course_id) values (83, 'homework', 89, 78);
insert into Category (category_id, category_name, weight, course_id) values (84, 'quiz', 56, 43);
insert into Category (category_id, category_name, weight, course_id) values (85, 'test', 93, 45);
insert into Category (category_id, category_name, weight, course_id) values (86, 'volunteer', 62, 88);
insert into Category (category_id, category_name, weight, course_id) values (87, 'quiz', 58, 63);
insert into Category (category_id, category_name, weight, course_id) values (88, 'test', 14, 86);
insert into Category (category_id, category_name, weight, course_id) values (89, 'extra credit', 27, 70);
insert into Category (category_id, category_name, weight, course_id) values (90, 'homework', 92, 90);
insert into Category (category_id, category_name, weight, course_id) values (91, 'quiz', 36, 73);
insert into Category (category_id, category_name, weight, course_id) values (92, 'quiz', 68, 76);
insert into Category (category_id, category_name, weight, course_id) values (93, 'volunteer', 10, 96);
insert into Category (category_id, category_name, weight, course_id) values (94, 'homework', 95, 96);
insert into Category (category_id, category_name, weight, course_id) values (95, 'project', 19, 2);
insert into Category (category_id, category_name, weight, course_id) values (96, 'volunteer', 71, 27);
insert into Category (category_id, category_name, weight, course_id) values (97, 'volunteer', 79, 8);
insert into Category (category_id, category_name, weight, course_id) values (98, 'volunteer', 44, 48);
insert into Category (category_id, category_name, weight, course_id) values (99, 'project', 50, 72);
insert into Category (category_id, category_name, weight, course_id) values (100, 'extra credit', 14, 42);
